### ISSUE TITLE
MouseEvent.movement(X|Y) isn't widely supported

### ISSUE THREAD

**Issue by perry** [zooniverse/transcribe#52]
The text annotation box is not draggable in Firefox.

You are using `MouseEvent.movement(X|Y)` which in Firefox the values are `undefined`. As a result of this, the [code](https://github.com/zooniverse/transcribe/blob/master/app/modules/classify/directives/text-annotation-edit.js#L66-L76) is returning `NaN` for the translation values.

**Comment by eatyourgreens** [comment]
Might just need prefixing to make it work cross-browser.
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent
