### ISSUE TITLE
Scrolling/zooming problematic in Safari and other possibly other browsers

### ISSUE THREAD

**Issue by VVH** [zooniverse/transcribe#62]
From alpha survey: 'Clear, though the centre field is too big. Scrolling is almost impossible because my cursor is constantly in the document and therefore magnifying it, rather than scrolling the page.'

**Comment by rogerhutchings** [comment]
This isn't a browser issue. This will be a full-page view once I've implemented the redesign (#29), so you won't need to scroll that page anymore.
