### ISSUE TITLE
Tilde function?

### ISSUE THREAD

**Issue by VVH** [zooniverse/transcribe#72]
One user writes: 'Maybe add the tilde function for illegibility to the algorithm (like in Old Weather)' -Apha Survey response to question 'What additional information or capability would you find helpful or interesting?'.

**Comment by rogerhutchings** [comment]
The only mention I can find of this is [on the forum](http://forum.oldweather.org/index.php?topic=3078.msg49657#msg49657). It just seems to be a convention, rather than a feature, and we already have the illegibility button - I'm not sure what more we can add.
